version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/lookquran.com
    ports:
      - 80:80
    depends_on:
      - lookquran

  lookquran:
    image: node:lts-alpine
    container_name: lookquran
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/app
    working_dir: /app
    command: /bin/sh -c "npm install -g nodemon && nodemon server"
    restart: on-failure
    expose:
      - "8080"
